theme: minima
title: Notes from your friendly neighborhood sister in TeX
description: Hi! I'm Emily, a high school sophomore (and an upcoming rising junior). I love molecular biology, programming, the performing arts, the ocean, Bo Burnham's music, Nerdfighteria and John Green's content, and reading a good book on the beach. I'm also obsessed with LaTeX to a slightly concerning extent, so this page is mostly a jumble of my random thoughts on LaTeX and its many features, but I am still learning, so please be patient with me! 
author: @leucinemymind
